Try to fix qi libraries building on melodic

diff --git a/ros_base/Dockerfile.from_roogp b/ros_base/Dockerfile.from_roogp
--- a/ros_base/Dockerfile.from_roogp
+++ b/ros_base/Dockerfile.from_roogp
@@ -6,6 +6,13 @@ RUN mkdir -p /tmp/gentoo/etc/portage/patches/ros-melodic/naoqi_libqi
 COPY patches/libqi-release.patch /tmp/gentoo/etc/portage/patches/ros-melodic/naoqi_libqi/libqi-release.patch
 RUN mkdir -p /tmp/gentoo/etc/portage/patches/ros-melodic/naoqi_libqicore
 COPY patches/libqicore-release.patch /tmp/gentoo/etc/portage/patches/ros-melodic/naoqi_libqicore/libqicore-release.patch
+# Given upstream there is no support for libqi and libqicore for melodic with boost > 1.70
+# We just take the kinetic one and patch it to be 'melodic'
+# To be fair, this should be PR'ed to ros-overlay, or even better, adapt the library in melodic to accept all boosts
+COPY ebuilds/naoqi_libqi-2.5.0-r3.ebuild $EPREFIX/usr/local/portage/ros-melodic/naoqi_libqi
+COPY ebuilds/naoqi_libqicore-2.3.1-r1.ebuild $EPREFIX/usr/local/portage/ros-melodic/naoqi_libqicore
+RUN echo ">naoqi_libqi-2.9" >> $EPREFIX/etc/portage/package.mask
+RUN echo ">naoqi_libqicore-2.9" >> $EPREFIX/etc/portage/package.mask
 
 #install libqi and libqicore
 RUN $PREFIXED emerge ros-melodic/naoqi_libqi
@@ -59,7 +66,8 @@ RUN $PREFIXED emerge ros-melodic/diagnostic_updater
 RUN $PREFIXED emerge ros-melodic/robot_state_publisher
 RUN $PREFIXED emerge ros-melodic/tf2_geometry_msgs
 
-# TODO: Include the building of naoqi_driver here
+# Trying to build naoqi_driver, but ignoring if it fails for now...
+RUN $PREFIXED emerge ros-melodic/naoqi_driver || true
 
 # Do that in separate packaging stage
 # RUN cd /tmp; tar czf sbre_robot_ros_melodic_gentoo_prefix_32.tar.gz gentoo
